/**
 * @class PaymentResult
 * @brief Data transfer object enclosing the final processing status payload returned by external payment gateways.
 * @details Unifies authorization decisions, remote transaction reference hashes, and localized error messages 
 * into a structured response shape used by billing workflows to determine order completion or failure paths.
 */
export class PaymentResult {
    /**
     * @brief Instantiates a structured payment processing transaction response token.
     * @param {boolean} [authorized=false] - Explicit processing status token confirming whether the bank approved the charge.
     * @param {string} [transactionCode=''] - Unique transaction tracking or approval code generated by the remote clearinghouse.
     * @param {string} [message=''] - Human-readable status narrative, context reason, or decline error log code.
     */
    constructor(authorized = false, transactionCode = '', message = '') {
        /** * @brief State flag confirming whether the financial acquisition handshake succeeded.
         * @type {boolean} 
         */
        this.authorized = authorized;

        /** * @brief Core auditing reference key used to trace the transaction back through financial ledgers.
         * @type {string} 
         */
        this.transactionCode = transactionCode;

        /** * @brief Descriptive informational text or reason explaining the specific authorization outcome.
         * @type {string} 
         */
        this.message = message;
    }
}