/**
 * @class SupportRequest
 * @brief Domain entity tracking customer care tickets, claims, and general service inquiries.
 * @details Models the lifecycle and metadata profile of user-submitted customer assistance claims, 
 * providing standardized hooks for managing submission pipelines and resolution states.
 */
export class SupportRequest {
    /** * @brief Unique primary indexing tracking key assigned to the support request entry.
     * @type {number} 
     */ 
    requestId;

    /** * @brief Operational categorization classification tag (e.g., 'refund', 'info', 'complaint').
     * @type {string} 
     */ 
    requestType; // 'refund', 'info', 'complaint'

    /** * @brief Detailed narrative text block describing the customer's core problem, question, or grievance.
     * @type {string} 
     */ 
    description;

    /** * @brief Active operational lifecycle state indicator configuration (e.g., 'open', 'closed').
     * @type {string} 
     */ 
    status; // 'open', 'closed'

    /** * @brief Explicit calendar date and time tracking when the ticket was generated by the user.
     * @type {Date} 
     */ 
    creationDate;

    /**
     * @brief Dispatches the service claim into the operational queue and persists state configurations.
     * @details Sets the initial structural lifecycle status tracking flag to 'open' and triggers 
     * database persistence routines to routing layers for representative triage.
     * @return {void}
     */
    submit() {
        this.status = 'open';
        // save to DB
    }

    /**
     * @brief Terminates the active support ticket lifecycle tracking state.
     * @details Modifies the internal status code configuration to 'closed', signaling to auditing 
     * queues that no further administrative actions or responses are required.
     * @return {void}
     */
    close() {
        this.status = 'closed';
    }
}