/**
 * @file PaymentResult.js
 * @brief Represents the data payload structure returned from an external financial clearinghouse transaction event.
 * @details Models transaction settlement outcomes, managing authorization states, tracking unique provider settlement tokens, 
 * and storing processing status text values.
 */
export class PaymentResult {
    /** * @brief Core authorization flag confirming if the banking processor cleared and locked the requested funds.
     * @type {boolean} 
     */ 
    authorized = false;

    /** * @brief Unique alphanumeric audit tracking token generated by the settlement gateway infrastructure.
     * @type {string} 
     */ 
    transactionCode = '';

    /** * @brief Detailed message string containing transaction error logs or successful transaction summaries.
     * @type {string} 
     */ 
    message = '';

    /**
     * @brief Instantiates a new payment processing result schema layout block.
     * @param {boolean} authorized - Baseline ledger clearance confirmation flag.
     * @param {string} transactionCode - Reference transaction index key generated by the clearinghouse.
     * @param {string} message - Explanatory status description or resolution log string.
     */
    constructor(authorized, transactionCode, message) {
        this.authorized = authorized;
        this.transactionCode = transactionCode;
        this.message = message;
    }
}